Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -53,5 +53,19 @@ jobs:
             echo {"AuthenticationKind": "UsernamePassword", "AuthenticationProperties": {"Username": "$(ClientId)", "Password": "$(ClientSecret)"}} > cred.json
             pqsdktools\tools\PQTest.exe set-credential --extension "bin\AnyCPU\Debug\s.mez" --queryFile "DataHubGraphQLConnector.query.pq" --prettyPrint < cred.json
             echo Running unit tests
-            pqsdktools\tools\PQTest.exe run-test --extension "bin\AnyCPU\Debug\s.mez" --queryFile "DataHubGraphQLConnector.query.pq" --prettyPrint
-            
+            pqsdktools\tools\PQTest.exe run-test --extension "bin\AnyCPU\Debug\s.mez" --queryFile "DataHubGraphQLConnector.query.pq" --prettyPrint > results.json
+        displayName: Run Tests
+        
+      - task: PowerShell@2
+        inputs:
+          targetType: 'inline'
+          script: |
+            $Results = Get-Content -Path results.json | ConvertFrom-Json
+            if ($Results.Status -eq "Passed") {
+                echo "Success"
+                exit 0
+            } else {
+                echo "Failure"
+                exit 1
+            }
+        displayName: Check Results
